# Writes build_date.h with today's date. Run on every build by the
# build_date target in CMakeLists.txt. file(CONFIGURE) only rewrites
# the header when its content changes, so it triggers a recompile at
# most once a day, yet the date shown is always the build date.
# Usage: cmake -DOUTPUT=<path to build_date.h> -P build_date.cmake

string(TIMESTAMP BUILD_DATE "%Y-%m-%d")
file(CONFIGURE OUTPUT "${OUTPUT}" CONTENT
"// Generated by build_date.cmake at build time, do not edit.
#ifndef BUILD_DATE_H
#define BUILD_DATE_H
#define Build_Date \"${BUILD_DATE}\"
#endif // BUILD_DATE_H
")
