// This header file contains declarations for the
// DDS waveform generator.
// Generated by : Optical_Theremin configuration tool version 20260926
// Run date and time : 2026-09-26 01:26:58
// Author : David Haley

#ifndef DDS_GENERATOR_H
#define DDS_GENERATOR_H

#include <stdint.h>

#define Sample_Rate 44100 // Sample rate in Hz
#define Highest_Note_MM 60
#define Lowest_Note_MM 380

typedef enum {
  Sine     = 0,
  Sine_2   = 1,
  Triangle = 2,
  Square   = 3
} Waveforms;

typedef struct {
  int16_t Left;
  int16_t Right;
} Audio_Sample;

// This function returns a single sample of audio each time it
// is called. The sample rate must be 44.1kHz. Waveform
// specifies the type of waveform to be produced and Distance
// the frequency. The maximum frequency is produced at
// Highest_Note_MM and the minimum frequency is produced at
// Lowest_Note_MM. If the measured distance is out of range,
// or more than Lowest_Note_MM, set Distance to
// Lowest_Note_MM. If the measured distance is less than
// Highest_Note_MM then set Distance to Highest_Note_MM.
Audio_Sample DDS_Generator (
  const Waveforms Waveform,
  const int Distance
);

#endif // DDS_GENERATOR_H
