// This file implements the DDS (direct digital synthesis)
// waveform generator for the Optical Theremin. The phase step
// and waveform tables are generated by the Optical_Theremin
// configuration tool (optical_theremin.adb).
// Author : David Haley

#include "dds_generator.h"
#include "dds_table.h"

// Number of bits the phase accumulator is shifted right to
// produce a Wave_Table index, 32 - log2 (Wave_Table length).
#define Phase_Shift 22

_Static_assert (sizeof (Wave_Table [0]) / sizeof (Wave_Table [0] [0]) ==
                  (1u << (32 - Phase_Shift)),
                "Phase_Shift does not match the Wave_Table length");
_Static_assert (sizeof (Wave_Table) / sizeof (Wave_Table [0]) ==
                  Square + 1,
                "Wave_Table does not have one row per waveform");
_Static_assert (Frequency_Count == Lowest_Note_MM - Highest_Note_MM + 1,
                "Phase_Step does not cover Highest_Note_MM .. Lowest_Note_MM");

// The phase accumulator is a 32 bit fixed point fraction of a
// cycle. It wraps naturally at the end of each cycle. Because it
// persists between calls, the waveform stays continuous (no
// clicks) when Distance or Waveform changes.
static uint32_t Phase = 0;

Audio_Sample __time_critical_func (DDS_Generator) (
  const Waveforms Waveform,
  const int Distance
) {
  int Clamped_Distance = Distance;
  Waveforms Selected_Waveform = Waveform;
  Audio_Sample Sample;

  if (Clamped_Distance < Highest_Note_MM) {
    Clamped_Distance = Highest_Note_MM;
  } else if (Clamped_Distance > Lowest_Note_MM) {
    Clamped_Distance = Lowest_Note_MM;
  } // Clamped_Distance < Highest_Note_MM
  if ((unsigned) Selected_Waveform > (unsigned) Square) {
    Selected_Waveform = Sine;
  } // (unsigned) Selected_Waveform > (unsigned) Square
  Sample.Left = Wave_Table [Selected_Waveform] [Phase >> Phase_Shift];
  Sample.Right = Sample.Left;
  Phase += Phase_Step [Clamped_Distance - Highest_Note_MM];
  return Sample;
} // DDS_Generator
