// This file implements the DDS (direct digital synthesis)
// waveform generator for the Optical Theremin. The phase step
// and waveform tables are generated by the Optical_Theremin
// configuration tool (optical_theremin.adb).
// Author : David Haley

// 20260929 : Phase_Shift moved to automatically generated header file. Ramp
// introduced smooth frequency transitions.

#include "dds_generator.h"
#include "dds_table.h"

_Static_assert (sizeof (Wave_Table [0]) / sizeof (Wave_Table [0] [0]) ==
                  (1u << (32 - Phase_Shift)),
                "Phase_Shift does not match the Wave_Table length");
_Static_assert (sizeof (Wave_Table) / sizeof (Wave_Table [0]) ==
                  Square + 1,
                "Wave_Table does not have one row per waveform");
_Static_assert (Frequency_Count == Lowest_Note_MM - Highest_Note_MM + 1,
                "Phase_Step does not cover Highest_Note_MM .. Lowest_Note_MM");

// The phase accumulator is a 32 bit fixed point fraction of a
// cycle. It wraps naturally at the end of each cycle. Because it
// persists between calls, the waveform stays continuous (no
// clicks) when Distance or Waveform changes.
static uint32_t Phase = 0;

// When Distance changes, the phase step glides linearly from its
// current value to the new target over Ramp_Length samples, rather
// than jumping. Ramping the phase step itself (not the distance in
// whole mm) gives a smooth glide however small the change, and a new
// target arriving mid-ramp starts from wherever the ramp has got to.
// Ramp_Length is a power of two so the per-sample increment needs a
// shift, not a division (the SDK divider routines are in flash).
// 2^11 = 2048 samples = 46 ms, just under the 50 ms main loop period,
// so a ramp normally completes before the next distance arrives.
#define Ramp_Shift 11
#define Ramp_Length (1 << Ramp_Shift)

// Previous_Distance starts outside the clamped range so the first
// call sets the target. Current_Step starts at 0, so at power up the
// pitch glides up from 0 Hz over the first ramp (while the volume is
// still at -103 dB).
static int Previous_Distance = 0;
static uint32_t Current_Step = 0;
static uint32_t Target_Step = 0;
static int32_t Step_Increment = 0;
static int Ramp_Count = 0;

Audio_Sample __time_critical_func (DDS_Generator) (
  const Waveforms Waveform,
  const int Distance
) {
  int Clamped_Distance = Distance;
  Waveforms Selected_Waveform = Waveform;
  Audio_Sample Sample;

  if (Clamped_Distance < Highest_Note_MM) {
    Clamped_Distance = Highest_Note_MM;
  } else if (Clamped_Distance > Lowest_Note_MM) {
    Clamped_Distance = Lowest_Note_MM;
  } // Clamped_Distance < Highest_Note_MM
  if ((unsigned) Selected_Waveform > (unsigned) Square) {
    Selected_Waveform = Sine;
  } // (unsigned) Selected_Waveform > (unsigned) Square
  if (Clamped_Distance != Previous_Distance) {
    Previous_Distance = Clamped_Distance;
    Target_Step = Phase_Step [Clamped_Distance - Highest_Note_MM];
    Step_Increment =
      (int32_t) (Target_Step - Current_Step) >> Ramp_Shift;
    Ramp_Count = Ramp_Length;
  } // Clamped_Distance != Previous_Distance
  if (Ramp_Count > 0) {
    Ramp_Count--;
    if (Ramp_Count == 0) {
      // Land exactly on the target, discarding the truncation error
      // accumulated from the shifted increment.
      Current_Step = Target_Step;
    } else {
      Current_Step += (uint32_t) Step_Increment;
    } // Ramp_Count == 0
  } // Ramp_Count > 0

  Sample.Left = Wave_Table [Selected_Waveform] [Phase >> Phase_Shift];
  Sample.Right = Sample.Left;
  Phase += Current_Step;
  return Sample;
} // DDS_Generator
