// This file implements the DDS (direct digital synthesis)
// waveform generator for the Optical Theremin. The phase step
// and waveform tables are generated by the Optical_Theremin
// configuration tool (optical_theremin.adb).
// Author : David Haley

// 20260929 : Phase_Shift moved to automatically generated header file. Ramp
// introduced smooth frequency transitions.
// 20261002 : 32 bit samples. Volume applied by a gain from Volume_Table,
// ramped in the same way as the frequency.
// 20261003 : Octave_Range moves the range by steps of one note adding to the
// index into the Phase_Step table.

#include "dds_generator.h"
#include "dds_table.h"

_Static_assert (sizeof (Wave_Table [0]) / sizeof (Wave_Table [0] [0]) ==
                  (1u << (32 - Phase_Shift)),
                "Phase_Shift does not match the Wave_Table length");
_Static_assert (sizeof (Wave_Table) / sizeof (Wave_Table [0]) ==
                  Square + 1,
                "Wave_Table does not have one row per waveform");
_Static_assert (Frequency_Count == Lowest_Note_MM - Highest_Note_MM + A0_A5 + 1,
                "Phase_Step does not cover every Octave_Range");
_Static_assert (Volume_Count == Mute_MM - Loud_MM + 1,
                "Volume_Table does not cover Loud_MM .. Mute_MM");

// The phase accumulator is a 32 bit fixed point fraction of a
// cycle. It wraps naturally at the end of each cycle. Because it
// persists between calls, the waveform stays continuous (no
// clicks) when Distance or Waveform changes.
static uint32_t Phase = 0;

// When Pitch_Distance changes, the phase step glides linearly from its
// current value to the new target over Ramp_Length samples, rather
// than jumping. Ramping the phase step itself (not the distance in
// whole mm) gives a smooth glide however small the change, and a new
// target arriving mid-ramp starts from wherever the ramp has got to.
// Ramp_Length is a power of two so the per-sample increment needs a
// shift, not a division (the SDK divider routines are in flash).
// 2^11 = 2048 samples = 46 ms, just under the 50 ms main loop period,
// so a ramp normally completes before the next distance arrives.
#define Ramp_Shift 11
#define Ramp_Length (1 << Ramp_Shift)

// Previous_Distance starts outside the clamped range so the first
// call sets the target. Current_Step starts at 0, so at power up the
// pitch glides up from 0 Hz over the first ramp (while the gain is
// also ramping up from 0).
static int Previous_Distance = 0;
static Octave_Ranges Previous_Octave_Range = Default_Octave_Range;
static uint32_t Current_Step = 0;
static uint32_t Target_Step = 0;
static int32_t Step_Increment = 0;
static int Ramp_Count = 0;

// The gain is ramped in the same way as the phase step, so a change
// of volume is spread over Ramp_Length samples rather than heard as
// a step. Gains are Q31, 0 .. 2^31 - 1, so the difference between two
// gains always fits in an int32_t.
static int Previous_Volume_Distance = 0;
static int32_t Current_Gain = 0;
static int32_t Target_Gain = 0;
static int32_t Gain_Increment = 0;
static int Gain_Ramp_Count = 0;

// Returns Sample x Gain / 2^31. The Cortex-M0+ only has a 32 x 32 -> 32
// bit multiply, and a 64 bit product would call a library routine in
// flash, so the product is formed from three 16 x 16 bit partial
// products, none of which overflow. The low x low product is less than
// one LSB of the result and is ignored, the result is within 3 LSB of
// exact.
static inline int32_t Apply_Gain (const int32_t Sample, const int32_t Gain) {
  const int32_t Sample_High = Sample >> 16;
  const uint32_t Sample_Low = (uint32_t) Sample & 0xFFFFu;
  const int32_t Gain_High = Gain >> 16;
  const int32_t Gain_Low = Gain & 0xFFFF;

  return 2 * (Sample_High * Gain_High) +
         ((Sample_High * Gain_Low) >> 15) +
         (int32_t) ((Sample_Low * (uint32_t) Gain_High) >> 15);
} // Apply_Gain

Audio_Sample __time_critical_func (DDS_Generator) (
  const Waveforms Waveform,
  const int Pitch_Distance,
  const int Volume_Distance,
  const Octave_Ranges Octave_Range
) {
  int Clamped_Distance = Pitch_Distance;
  Octave_Ranges Clamped_Range = Octave_Range;
  int Clamped_Volume_Distance = Volume_Distance;
  Waveforms Selected_Waveform = Waveform;
  Audio_Sample Sample;

  if (Clamped_Distance < Highest_Note_MM) {
    Clamped_Distance = Highest_Note_MM;
  } else if (Clamped_Distance > Lowest_Note_MM) {
    Clamped_Distance = Lowest_Note_MM;
  } // Clamped_Distance < Highest_Note_MM
  if ((unsigned) Clamped_Range > (unsigned) A0_A5) {
    Clamped_Range = Default_Octave_Range;
  } // (unsigned) Clamped_Range > (unsigned) A0_A5)
  if ((unsigned) Selected_Waveform > (unsigned) Square) {
    Selected_Waveform = Default_Waveform;
  } // (unsigned) Selected_Waveform > (unsigned) Square
  if (Clamped_Distance != Previous_Distance ||
      Clamped_Range != Previous_Octave_Range) {
    Previous_Distance = Clamped_Distance;
    Previous_Octave_Range = Clamped_Range;
    // The range offsets the index into Phase_Step.
    Target_Step = Phase_Step [Clamped_Distance - Highest_Note_MM +
      Clamped_Range];
    Step_Increment =
      (int32_t) (Target_Step - Current_Step) >> Ramp_Shift;
    Ramp_Count = Ramp_Length;
  } // Clamped_Distance != Previous_Distance || ...
  if (Ramp_Count > 0) {
    Ramp_Count--;
    if (Ramp_Count == 0) {
      // Land exactly on the target, discarding the truncation error
      // accumulated from the shifted increment.
      Current_Step = Target_Step;
    } else {
      Current_Step += (uint32_t) Step_Increment;
    } // Ramp_Count == 0
  } // Ramp_Count > 0

  if (Clamped_Volume_Distance < Loud_MM) {
    Clamped_Volume_Distance = Loud_MM;
  } else if (Clamped_Volume_Distance > Mute_MM) {
    Clamped_Volume_Distance = Mute_MM;
  } // Clamped_Volume_Distance < Loud_MM
  if (Clamped_Volume_Distance != Previous_Volume_Distance) {
    Previous_Volume_Distance = Clamped_Volume_Distance;
    Target_Gain = Volume_Table [Clamped_Volume_Distance - Loud_MM];
    Gain_Increment = (Target_Gain - Current_Gain) >> Ramp_Shift;
    Gain_Ramp_Count = Ramp_Length;
  } // Clamped_Volume_Distance != Previous_Volume_Distance
  if (Gain_Ramp_Count > 0) {
    Gain_Ramp_Count--;
    if (Gain_Ramp_Count == 0) {
      Current_Gain = Target_Gain;
    } else {
      Current_Gain += Gain_Increment;
    } // Gain_Ramp_Count == 0
  } // Gain_Ramp_Count > 0

  Sample.Left = Apply_Gain (
    Wave_Table [Selected_Waveform] [Phase >> Phase_Shift], Current_Gain);
  Sample.Right = Sample.Left;
  Phase += Current_Step;
  return Sample;
} // DDS_Generator
