// This header file contains declarations for the
// DDS waveform generator.
// Generated by : Optical_Theremin configuration tool version 20261002
// Run date and time : 2026-10-02 18:55:23
// Author : David Haley

#ifndef DDS_GENERATOR_H
#define DDS_GENERATOR_H

#include <stdint.h>

#define PIO_Clock_Divisor 22 // PIO divisor to set bit rate
#define Sample_Rate 4.43892045454545E+04 // Sample rate in Hz
#define Sample_Size 32 // Sample size in bits

#define Highest_Note_MM 60 // Distance for highest frequency
#define Lowest_Note_MM 360 // Distance for lowest frequency

#define Loud_MM 100 // Distance for maximum voume
#define Mute_MM 355 // Distance to mute output

typedef enum {
  Sine     = 0,
  Sine_2   = 1,
  Triangle = 2,
  Square   = 3
} Waveforms;

typedef struct {
  int32_t Left;
  int32_t Right;
} Audio_Sample;

// This function returns a single sample of audio each time it
// is called. The sample rate must be 4.43892045454545E+04Hz. Waveform
// specifies the type of waveform to be produced. Tone_Distance
// specifies the frequency. The maximum frequency is produced at
// Highest_Note_MM and the minimum frequency is produced at
// Lowest_Note_MM. If the measured distance is out of range,
// or more than Lowest_Note_MM, set Distance to
// Lowest_Note_MM. If the measured distance is less than
// Highest_Note_MM then set Distance to Highest_Note_MM.
// Volume_Distance defines the output volume, for Loud_MM the
// the maximum output level is produced and for Muted_MM, no
// output is produced.
Audio_Sample DDS_Generator (
  const Waveforms Waveform,
  const int Tone_Distance,
  const int Volume_Distance
);

#endif // DDS_GENERATOR_H
